---

# install confd package from repo
- name: confd | download and copy "confd" binary file to /usr/local/bin/
  get_url:
    url: '{{ item }}'
    dest: /usr/local/bin/confd
    mode: u+x,g+x,o+x
    timeout: 60
    validate_certs: no
  loop:
    - '{{ confd_package_repo }}'
  environment: '{{ proxy_env | default({}) }}'
  when: installation_method == "repo" and confd_package_repo | length > 0
  tags: [ get_confd, confd ]

# install confd package from file
- name: confd | copy "confd" binary file to /usr/local/bin/
  copy:
    src: '{{ confd_package_file }}'
    dest: /usr/local/bin/confd
    mode: u+x,g+x,o+x
  when: installation_method == "file" and confd_package_file | length > 0
  tags: [ get_confd, confd ]

- name: confd | create conf directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /etc/confd/conf.d
    - /etc/confd/templates
  tags: [ confd_dir, confd_conf, confd ]

- name: confd | generate conf file "/etc/confd/confd.toml"
  template:
    src: templates/confd.toml.j2
    dest: /etc/confd/confd.toml
  tags: [ confd_toml, confd_conf, confd ]

- name: confd | generate conf file "/etc/confd/conf.d/haproxy.toml"
  template:
    src: templates/haproxy.toml.j2
    dest: /etc/confd/conf.d/haproxy.toml
  tags: [ haproxy_toml, confd_conf, confd ]

- name: confd | generate template "/etc/confd/templates/haproxy.tmpl"
  template:
    src: templates/haproxy.tmpl.j2
    dest: /etc/confd/templates/haproxy.tmpl
  tags: [ haproxy_tmpl, confd_conf ,confd ]

- name: confd | copy systemd service file
  template:
    src: templates/confd.service.j2
    dest: /etc/systemd/system/confd.service
  tags: [ confd_service, confd ]

- name: confd | restart systemd service
  systemd:
    daemon_reload: yes
    name: confd
    enabled: yes
    state: restarted
  tags: [ confd_restart, confd ]
